name: Generate Changelog
description: Generate changelog for a module based on its previous tag and included scopes
inputs:
  prefix:
    description: "See https://github.com/aklinker1/generate-changelog/blob/main/src/types/options.ts"
  suffix:
    description: "See https://github.com/aklinker1/generate-changelog/blob/main/src/types/options.ts"
  fixHeading:
    description: "See https://github.com/aklinker1/generate-changelog/blob/main/src/types/options.ts"
  featHeading:
    description: "See https://github.com/aklinker1/generate-changelog/blob/main/src/types/options.ts"
  breakingChangeHeading:
    description: "See https://github.com/aklinker1/generate-changelog/blob/main/src/types/options.ts"
  module:
    description: "See https://github.com/aklinker1/generate-changelog/blob/main/src/types/options.ts"
  scopes:
    description: "See https://github.com/aklinker1/generate-changelog/blob/main/src/types/options.ts"

outputs:
  prevVersion:
    description: The suggested prev version
  prevTag:
    description: Commits after this tag were used to generate the changelog
  changelog:
    description: The filtered changelog
  skipped:
    description: Will be set to true when the generated changelog includes no fixes or features
  nextVersion:
    description: The suggested next version based on the changes
  nextTag:
    description: The suggested tag to create a release with

runs:
  using: node16
  main: index.js
