name: Publish
on: [workflow_dispatch]

jobs:
  validate:
    uses: ./.github/workflows/validate.yml

  release:
    name: Release
    runs-on: ubuntu-22.04
    needs: [validate]
    outputs:
      skipped: ${{ steps.changelog.outputs.skipped }}
      nextVersion: ${{ steps.changelog.outputs.nextVersion }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - id: changelog
        name: Generate Changelog
        uses: ./.github/actions/generate-changelog
